version: 0.2

phases:

  pre_build:
    commands:
      - echo logging into dockerhub
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - git clone https://github.com/Gangadhar-7/Backend-Deployment-Repo.git
      
  build:
    commands:
      - TAG_FROM_MANIFEST=$(grep -oP 'gangadhar0416/backend:\K[^"]+' Backend-Deployment-Repo/kubernetes-manifests/backend-deployment.yaml)
      - NEW_TAG=$((TAG_FROM_MANIFEST + 1))
      - sed -i "s@gangadhar0416/backend:$TAG_FROM_MANIFEST@gangadhar0416/backend:$NEW_TAG@" Backend-Deployment-Repo/kubernetes-manifests/backend-deployment.yaml
      - docker build -t gangadhar0416/backend .
      - docker tag gangadhar0416/backend gangadhar0416/backend:$NEW_TAG
  post_build:
    commands:
      - docker push gangadhar0416/backend:$NEW_TAG
      - cd Backend-Deployment-Repo
      - git config --local user.name "Gangadhar-7"
      - git config --local user.email "gangadharm877@gmail.com"
      - git remote set-url origin https://Gangadhar-7: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@github.com/Gangadhar-7/Backend-Deployment-Repo.git

      - git add kubernetes-manifests/backend-deployment.yaml
      - git commit -m "Update environment variable in deployment.yaml"
      - git push origin main
artifacts:
  files: Dockerfile



































# version: 0.2
  
# phases:
#   pre_build :
#     commands:
#       - echo logging into dockerhub
#       - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   build:
#     commands:
#       - echo building images
#       - docker build -t backend .
#       - docker tag backend gangadhar0416/backend
#   post_build:
#     commands:
#       - echo build completed and pushing the image .
#       - docker push gangadhar0416/backend